image: nixos/latest
environment:
  NIX_CONFIG: "experimental-features = nix-command flakes"
sources:
  - https://git.sr.ht/~luisholanda/kiso
tasks:
  - setup: |
      cd kiso
      nix flake archive
  - build: |
      cd kiso
      nix build -j auto .#kiso
  - checks: |
      cd kiso
      nix develop -c pre-commit run --all --verbose
  - benchmark-echo: |
      cd kiso
      nix run .#benchmark-echo
